name: Build bot release
on: push
jobs:
    build-bot:
      permissions: write-all
      name: Build Bot
      runs-on: ubuntu-latest
      container: node:16
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build Bot Exe
        run: npm run build

      # Upload artifact
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: new-bot-release
          path: ./bot.exe

    # Create release job
    release-project:
      permissions: write-all
      name: Release Project
      runs-on: ubuntu-latest
      needs: build-bot
      steps:

      # Download artifact
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: new-bot-release

      # View contents of downloaded artifact
      - name: View content
        run: ls -R

      # Create GitHub release
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      
      # Upload asset to release
      - name: Archive bot release content
        uses: thedoctor0/zip-release@master
        with:
          filename: bot.zip

      # Upload asset to release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./bot.zip
          asset_name: bot-v${{ github.run_number }}.zip
          asset_content_type: application/zip